### ISSUE TITLE
Deleting multiple selected rules in UI Rules tab with Ctrl+click deletes the wrong rules

### ISSUE THREAD

**Issue by e3dio** [evilsocket/opensnitch#1245]
When you CTRL + Click to select multiple rules (selected rules have the row highlighted) and then delete, it deletes different rules than those selected. If you select multiple rules by Mouse Down + Drag it deletes the correct rules. CTRL + Click is the most convenient method to select rules, this type of selection and deletion should be properly supported

**Comment by gustavo-iniguez-goya** [comment]
Hi @e3dio ,

Fixed. Thanks for reporting it. Fixed in latest release https://github.com/evilsocket/opensnitch/releases/tag/v1.6.7

**Comment by e3dio** [comment]
I'm still seeing issues deleting rules with 1.6.7, even without ctrl+click, deleting multiple selected rules deletes wrong rules. Now I only delete 1 rule at a time to prevent UI from randomly deleting rules, or if I apply a filter it seems to limit the random deletion to that filter

**Comment by gustavo-iniguez-goya** [comment]
I remember having this issue long time ago, like 3-4 years ago. But as far as I can tell it works fine now, at least I can't reproduce it.

If you change node's LogLevel to INFO and monitor /var/log/opensnitchd.log, you'll see what rules did the daemon receive to be deleted. That way you can be sure what you selected from the GUI, what the daemon received and what was deleted.

It'll also be helpful to debug this issue if you could post:
 - what kind of rules are the problematic ones (temporary rules, permanent rules, etc).
 - if you have a limit of rules to display.
 - if you filtered the rules by a term.
 - and if you reproduce it by selecting only the visible rules.

**Comment by e3dio** [comment]
Ok I took some before and after screenshots to show the issue. I opened Chromium and allowed / denied various connections to create about 20 rules. I filtered rules on "chromium" for this example. I selected a group of 5 rules to delete, see screenshot (1). I pressed delete and clicked ok, then took screenshot (2). This shows that instead of the 5 rules selected, it deleted every other rule starting from the 1st selected rule, deleting 5 rules total, 3 rules correctly, 2 rules wrong. Screenshot (3) shows the logs show the 3 correct rules deleted and the 2 wrong rules also deleted at timestamp 00:53:59

![os1](https://github.com/user-attachments/assets/33c837c7-5aca-4a59-a22e-e95118c5eb03)
![os2](https://github.com/user-attachments/assets/9db20152-8f37-47e4-a3f9-5e6e35c46b27)
![os3](https://github.com/user-attachments/assets/160e1a2a-6898-41e4-8946-eb0cacebc1bf)

**Comment by e3dio** [comment]
Tried it again deleting 17 rules, it deleted every other rule, like 1, 3, 5, 7, 9 etc, so something going on with that. Unfortunately I have no experience with Python/Qt

**Comment by e3dio** [comment]
I think I know what could cause issue. As you delete rows the index of the rows change. If you take the index after you delete a row, this would give the pattern as shown in test. This must be the explanation :)

**Comment by e3dio** [comment]
delete rule, get rule at index that is now invalid, repeat, etc https://github.com/evilsocket/opensnitch/blob/337b81a89b48c32afa07fe6ff08ce5f5964d456b/ui/opensnitch/dialogs/stats.py#L1569-L1572

**Comment by e3dio** [comment]
If this were Html/JavaScript it would be a simple 1 line of code to correctly delete rules, this qt/python stuff is too much but that is my web dev perspective

**Comment by gustavo-iniguez-goya** [comment]
thank you @e3dio !

I've tried to reproduce it but no luck. I've tested the PR and worked as expected, so all good :)
