### ISSUE TITLE
Deleting all rules only deletes some of them

### ISSUE THREAD

**Issue by tredondo** [evilsocket/opensnitch#1272]
**Describe the bug**
 - OpenSnitch version 1.6.7
 - OS: Fedora
 - Window Manager: KDE

**To Reproduce**
1. Go to 'Rules -> Temporary'
2. Click a rule
3. Press Ctrl+A
4. Press Del

Already an error here, the prompt says "You are about to delete **this rule**" (singular), when multiple rules are selected.

![Image](https://github.com/user-attachments/assets/ca7a38f5-edfc-41ba-812d-c99f2890ed5e)

5. Press Yes to delete all rules.
6. Notice that many rules are left:

**Screenshots**

![Image](https://github.com/user-attachments/assets/2af3779e-640f-40ba-acbc-d6f55bd4f2a3)

**Comment by e3dio** [comment]
There is a serious bug with deleting rules that I explained here https://github.com/evilsocket/opensnitch/issues/1245 He did not do a release with the fix yet, you need this PR https://github.com/evilsocket/opensnitch/pull/1252

**Comment by e3dio** [comment]
@tredondo Can you confirm issue is resolved in [v1.6.8](https://github.com/evilsocket/opensnitch/releases/tag/v1.6.8)

**Comment by tredondo** [comment]
@e3dio yes, deleting worked correctly in 1.6.8 for all selected rules I tested. The only issue was the singular in the message

![Image](https://github.com/user-attachments/assets/7dc72149-5b02-4079-a0e2-eab6829f8117)

**Comment by pkw365** [comment]
Deletion bug is still present.
Tested  on xfce / debian 12+13 / ubuntu 22+24+sid.

**Comment by scarylizard** [comment]
The bug is still present with daemon version 1.7.2, running on NixOS unstable.

**Comment by tredondo** [comment]
As of v1.8.0, right clicking deselected all rules, so only one will be deleted.

https://github.com/user-attachments/assets/5fa39191-4234-41ca-82cc-eb402e58f13a

**Comment by gustavo-iniguez-goya** [comment]
finally added.

Now it's possible to select all rows with Ctrl+a and apply actions on the selection. Also when deleting rules, it'll display the number of rows that will be deleted.

There's an issue when pressing Ctrl+a: the Ctrl key must be held while pressing 'a'. Sometimes it seems that I briefly release Ctrl before pressing 'a', which invalidates the SelectAll key combination.
I'll try to improve this behaviour.
