### ISSUE TITLE
GUI Scaling

### ISSUE THREAD

**Issue by Aiyarree** [evilsocket/opensnitch#182]
Please make it correctly scale with higher resolutions.
Even at simple 200% it is unusable - what makes it next to worthless in daily work.

- Tested with Ubuntu Bionic and Budgie Desktop on 4k -

**Comment by MiWCryptAnalytics** [comment]
Fixed with #203

**Comment by B4rabbas** [comment]
Builded today and I have the issue still there
![screenshot openshot](https://user-images.githubusercontent.com/36156012/49332728-ae2d7a80-f5b2-11e8-80e5-34120f5f6dcf.png)

**Comment by Bezierr** [comment]
I can confirm that the issue is still there with the latest version of OpenSnitch: UI does not scale to 200% on Linux Mint Mate 20.2 .

**Comment by gustavo-iniguez-goya** [comment]
hey @B4rabbas , the title of that dialog reads "v1.0.0b" is that correct? which version did you build?
