### ISSUE TITLE
unable to start opensnitch-daemon

### ISSUE THREAD

**Issue by Brutus11111** [evilsocket/opensnitch#204]
Hi, 

When I start the daemon, I get the following messages:

```
[2018-09-20 14:53:43]  IMP  Starting opensnitch-daemon v1.0.0b
[2018-09-20 14:53:43]  INF  Loading rules from /etc/opensnitchd/rules ...
[2018-09-20 14:53:43]  !!!  Error while creating queue #0: Error unbinding existing q handler from AF_INET protocol family: invalid argument
[2018-09-20 14:54:14]  IMP  Starting opensnitch-daemon v1.0.0b
[2018-09-20 14:54:14]  INF  Loading rules from /etc/opensnitchd/rules ...
[2018-09-20 14:54:14]  !!!  Error while creating queue #0: Error unbinding existing q handler from AF_INET protocol family: invalid argument
[2018-09-20 14:54:44]  IMP  Starting opensnitch-daemon v1.0.0b
[2018-09-20 14:54:44]  INF  Loading rules from /etc/opensnitchd/rules ...
[2018-09-20 14:54:44]  !!!  Error while creating queue #0: Error unbinding existing q handler from AF_INET protocol family: invalid argument
[2018-09-20 14:55:14]  IMP  Starting opensnitch-daemon v1.0.0b
[2018-09-20 14:55:14]  INF  Loading rules from /etc/opensnitchd/rules ...
[2018-09-20 14:55:14]  !!!  Error while creating queue #0: Error unbinding existing q handler from AF_INET protocol family: invalid argument
[2018-09-20 14:55:44]  IMP  Starting opensnitch-daemon v1.0.0b
[2018-09-20 14:55:44]  INF  Loading rules from /etc/opensnitchd/rules ...
[2018-09-20 14:55:44]  !!!  Error while creating queue #0: Error unbinding existing q handler from AF_INET protocol family: invalid argument
[2018-09-20 14:56:15]  IMP  Starting opensnitch-daemon v1.0.0b
[2018-09-20 14:56:15]  INF  Loading rules from /etc/opensnitchd/rules ...
[2018-09-20 14:56:15]  !!!  Error while creating queue #0: Error unbinding existing q handler from AF_INET protocol family: invalid argument
```

**Comment by lepz0r** [comment]
same here

**Comment by jfreax** [comment]
I get the exact same error. Any ideas?

```
# uname -a
Linux thinx1 4.20.0-gentoo #1 SMP Thu Dec 27 11:23:49 CET 2018 x86_64 Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz GenuineIntel GNU/Linux
```

**Comment by gustavo-iniguez-goya** [comment]
I think this problem is fixed with latest packages.

**Comment by vikgac** [comment]
Still have this exact same  error   v1.3.6.  Mobile Debian on Pinephone.  Will you reopen issue and fix?

**Comment by gustavo-iniguez-goya** [comment]
Hi @vikgac ,

First provide some logs:

-  Post /var/log/opensnitchd.log
- `lsmod | grep -i queue`
-  `cat /proc/net/ip_tables_targets`
-  `cat /proc/net/netfilter/nfnetlink_queue`
- `grep NFQUEUE /boot/config-$(uname -r)`
- `dpkg -l 'libnetfilter-queue*'`

thank you!

**Comment by morfikov** [comment]
I had the same error (`Error while creating queue #0: Error unbinding existing q handler from AF_INET protocol family: invalid argument`) and it went away after enabling the following options in the kernel (I'm not sure whether all of them are required, but I selected all of them):

```
CONFIG_NFT_QUEUE=y
CONFIG_NETFILTER_NETLINK_QUEUE=y
CONFIG_NETFILTER_XT_TARGET_NFQUEUE=y
```

**Comment by gustavo-iniguez-goya** [comment]
Yeah @morfikov , those options usually are configured as modules in the majority of distributions, so when the iptables rules are inserted , the needed modules are loaded.

What distro are you using? Did you compile a custom kernel or you just used the one shipped with your distro?

**Comment by morfikov** [comment]
I'm using debian, but with my own kernel.

**Comment by gustavo-iniguez-goya** [comment]
aaah, I see. Thank you for providing this information! I suspected that it could be caused for not having support for NFQUEUE in the kernel, but I didn't know for sure. I'll update the wiki with this info.

**Comment by awsms** [comment]
> aaah, I see. Thank you for providing this information! I suspected that it could be caused for not having support for NFQUEUE in the kernel, but I didn't know for sure. I'll update the wiki with this info.

was this added anywhere to the wiki? i wasted a few time before finding out this info here
