### ISSUE TITLE
Pixellated icon in KDE Large Icons task switcher

### ISSUE THREAD

**Issue by Richard-Payne** [evilsocket/opensnitch#302]
**Describe the bug**
The large icons task switcher in KDE is displaying an upscaled icon for opensnitch.
![image](https://user-images.githubusercontent.com/6730730/102010121-ecc6a580-3d33-11eb-8071-73cda4805439.png)

**To Reproduce**
Run Manjaro.  Select the Large Icons task switcher
![image](https://user-images.githubusercontent.com/6730730/102010149-1d0e4400-3d34-11eb-9307-be92859c5bd9.png)
Press alt-tab

**Expected behavior (optional)**
A non-pixelated 512x512 icon to be displayed.

**OS (please complete the following information):**
 - OS: Manjaro
 - Window Manager: KDE
 - Kernel version: Linux 5.8.18-1-MANJARO #1 SMP PREEMPT Sun Nov 1 14:10:04 UTC 2020 x86_64 GNU/Linux
 - Version: rolling

**Additional context**
I thought this might be an easy one to fix, and I could just submit a PR for you, but my Python skills are lacking.  

I have tried switching the setup.py script to placing the opensnitch-ui.png file in 512x512 hicolor directory, instead of 48x48.  That didn't help.

I read that KWin reads icons from the Window, not the desktop file.  Interestingly, xprop reveals the issue:
![image](https://user-images.githubusercontent.com/6730730/102010294-2946d100-3d35-11eb-8902-97df1bfa2f6a.png)

Compare to Firefox:
![image](https://user-images.githubusercontent.com/6730730/102010313-3ebbfb00-3d35-11eb-948d-ee490cc1bd06.png)
![image](https://user-images.githubusercontent.com/6730730/102010320-4a0f2680-3d35-11eb-9d79-0b29c00398af.png)
![image](https://user-images.githubusercontent.com/6730730/102010330-52676180-3d35-11eb-82bf-ede488353233.png)
![image](https://user-images.githubusercontent.com/6730730/102010336-5f845080-3d35-11eb-8a2e-23d689147ec9.png)

The Firefox window has multiple icon resources attached.  OpenSnitch only has the 48x48 icon. 
However, I'm not sure why this is the case.  From what I can see, the window setup code is loading the window icon from ui/opensnitch/res/icon-white.svg.  Lacking any knowledge of how Qt handles svg sizing for icons, I tried switching it out for the png version which is sized at 512x512 already.  That made no difference.  I also tried editing the svg file manually to set the size.  This didn't help.

**Comment by gustavo-iniguez-goya** [comment]
Hi Richard! thank you for reporting this.

I'll try to reroduce it and find a way of solving it.

**Comment by gustavo-iniguez-goya** [comment]
Ok, solved with this snippet under stats.py, __init__:222:

```
app_icon = QtGui.QIcon("/usr/share/icons/hicolor/scalable/apps/opensnitch-ui.svg")
self.setWindowIcon(app_icon)
```

But maybe it's better to add it as resource of the dialog definition, instead of hardcoding it there. I'll test both options.

**Comment by Richard-Payne** [comment]
That doesn't fix it for me.  Is there than just snippet?
Or maybe my build is no good.  I'm doing:
```
make clean
make
sudo make install
```
The binary in /usr/bin seems to be updated.  I am getting a warning during the build:
```
protoc -I. ui.proto --go_out=plugins=grpc:../daemon/ui/protocol/
2020/12/13 16:08:20 WARNING: Missing 'go_package' option in "ui.proto", please specify:
        option go_package = ".;protocol";
A future release of protoc-gen-go will require this be specified.
See https://developers.google.com/protocol-buffers/docs/reference/go-generated#package for more information.
```
Not sure if it's relevant.

**Comment by gustavo-iniguez-goya** [comment]
> Is there more than just that snippet?

nope, only those 2 lines after https://github.com/evilsocket/opensnitch/blob/master/ui/opensnitch/dialogs/stats.py#L210 in `/usr/lib/python3.7/opensnitch/dialogs/stats.py`

tested with kde plasma 5.19.5 , framework 5.74.0

If you have it installed and running, edit `/usr/lib/python3.7/opensnitch/dialogs/stats.py` , close the GUI completely (not just the stats window) and relaunch it again.

By the way, don't you use the AUR package?

**Comment by Richard-Payne** [comment]
I had the AUR package originally but I removed it because I planned to fix it myself and submit a PR, so I was build and installing the package from a repo clone using make.

I'm on plasma 5.20.4, framework 5.76.0.

I just installed the opensnitch-git package but there is no opensnitch dir in /usr/lib/python3.8.

**Comment by gustavo-iniguez-goya** [comment]
It would be good if you could identify where is located the installation of the GUI, maybe you have several installations at different locations. I don't know about the AUR package, but installing it manually should be under /usr/local/lib/python3 or python3.x (whatever /usr/bin/python3 points to). It could also be located under /usr/lib/pythonX.Y/ 

Once that solved, try again modifying the stats.py which is being used to show the window, either adding the lines above or :
```
app_icon = QtGui.QIcon(":/icon-white.png") 
self.setWindowIcon(app_icon)
```
which should load the default icon from the resources store of size 512px.

I'll test it on more systems.

**Comment by Richard-Payne** [comment]
Aha, problem solved.

My sys.path reports: ['', '/usr/lib/python38.zip', '/usr/lib/python3.8', '/usr/lib/python3.8/lib-dynload', '/home/richard/.local/lib/python3.8/site-packages', '/usr/lib/python3.8/site-packages']

There is: /usr/lib/python3.8/site-packages/opensnitch/ which it is taking in preference to the one /usr/lib/python3.8.

**Comment by gustavo-iniguez-goya** [comment]
Sorry, it should be:

```
app_icon = QtGui.QIcon(":/pics/icon-white.png") 
self.setWindowIcon(app_icon)
```

If that works (it should load the 512px icon), I can embed the .svg and use it as the window icon.

**Comment by Richard-Payne** [comment]
_Sorry, this response should have been posted 6 days ago but apparently I forgot to hit send!_

Aha, problem solved.

My sys.path reports: ['', '/usr/lib/python38.zip', '/usr/lib/python3.8', '/usr/lib/python3.8/lib-dynload', '/home/richard/.local/lib/python3.8/site-packages', '/usr/lib/python3.8/site-packages']

There is: /usr/lib/python3.8/site-packages/opensnitch/ which it is taking in preference to the one /usr/lib/python3.8.

**Comment by gustavo-iniguez-goya** [comment]
ok, good news then. But just for clarification, you have had to add this snippet, haven't you?
```
app_icon = QtGui.QIcon(":/icon-white.png") 
self.setWindowIcon(app_icon)
```

**Comment by Richard-Payne** [comment]
Yes, I did.  It's problem solved on both fronts.  Your code snippet fixed the reported issue and the noticing the python sys.path issue allowed me to apply your fix without waiting for it to be included in a proper release.

Thanks

**Comment by gustavo-iniguez-goya** [comment]
ok, I'll add the change so others can benefit also from it. Thank you!
